### ISSUE TITLE
Bei Auswahl einer Startkategorie verschwinden die Checkboxen und die Multi-Aktionsauswahl unten

### ISSUE THREAD

**Issue by iceman-fx** [novinet-git/rex_mediapool_megapermissions#2]
Wenn man eine Mediakat als Startpfad vorwählt, dann hat der Redakteur keine Checkboxen und Multi-Aktionsauswahl unten mehr.

![1](https://user-images.githubusercontent.com/4291047/211011505-bd3274b8-4b4a-4ce9-a5e4-6a88c2abae74.png)

**Comment by joachimdoerr** [comment]
f867a9b4f67bb7ca22981ee5472d9a0315f6202b
