### ISSUE TITLE
Problem mit aktueller Version für Rex 5.15

### ISSUE THREAD

**Issue by iceman-fx** [novinet-git/rex_mediapool_megapermissions#4]
Nach Update auf Rex5.15 und Ersetzung des MP mit dieser aktuellen Version kommt folgender Fehler beim Aufruf des MP:

12.12.2023 08:31:09
AssertionError | assert(isset($rexFileCategory) && is_int($rexFileCategory))
Datei: redaxo/src/addons/mediapool/pages/media.php:3
URL: https://www.domain.de/redaxo/index.php?page=mediapool/media&opener_input_field=

**Comment by joachimdoerr** [comment]
@iceman-fx ich kann nach dem update auf v2.14 das Problem nicht nachstellen.
